### ISSUE TITLE
improve docs

### ISSUE THREAD

**Issue by oakmac** [cljsinfo/cljs.info#45]
The following docs have `TODO`s in them and need to be reviewed / improved.

```
# grep -Irl "TODO" .
./cljs.core_-GT.cljsdoc
./cljs.core_-GTGT.cljsdoc
./cljs.core_apply.cljsdoc
./cljs.core_as-GT.cljsdoc
./cljs.core_comp.cljsdoc
./cljs.core_def.cljsdoc
./cljs.core_doall.cljsdoc
./cljs.core_doseq.cljsdoc
./cljs.core_fn.cljsdoc
./cljs.core_for.cljsdoc
./cljs.core_identity.cljsdoc
./cljs.core_ns.cljsdoc
./cljs.core_partition.cljsdoc
./cljs.core_take-last.cljsdoc
./cljs.core_to-array-2d.cljsdoc
./cljs.core_when-first.cljsdoc
```

**Comment by shaunlebron** [comment]
I'm going to close this issue here.  Some points:

- We've talked with zachary from clojuredocs and reid from grimoire and we all agreed to use CC0 to license the examples, meaning we can all trade them.
- the following screenshot is taken from the docs view for [`cljs.core/apply`](https://github.com/cljsinfo/cljs-api-docs/blob/catalog/refs/cljs.core_apply.md), which has links to the respective entry in clojuredocs, grimoire, crossclj for example referencing, and the links at the bottom for editing and learning how to edit.

<img width="793" alt="screen shot 2015-07-27 at 3 23 01 pm" src="https://cloud.githubusercontent.com/assets/116838/8916781/656d77ea-3473-11e5-93d2-a611b3ca1d48.png">
